### ISSUE TITLE
Add Edit Query Functionality

### ISSUE THREAD

**Issue by b-f-chan** [supercluster-covid-data-portal/ui#11]
Add functionality for user to edit a saved query

- Only possible if they have logged in
- Once user clicks the My Queries drop-down, they can see a list of their queries
- Beside each query will be a control (e.g. pencil/edit icon) to edit the query
- If they click edit, modal is displayed allowing them to ONLY edit the name (like KidsFirst)
- Add logic to make the request to the DNAstack API to update the query once they confirm the modal

Wireframes + API details in spec:
https://wiki.oicr.on.ca/display/CC/COVID+Cloud+Data+Explorer+Requirements#COVIDCloudDataExplorerRequirements-ModifyinganExistingQuery

**Comment by justincorrigible** [comment]
For the issue described here by @b-f-chan: https://github.com/supercluster-covid-data-portal/ui/issues/10#issuecomment-982792074.

> 1. Save two different queries with different names
> 2. Load Query A
> 3. With Query A loaded, rename Query B using the My Queries drop-down
> 4. Now try to switch view and load Query B
> 5. BUG: Query B does not load, and Query A remains on screen 

The issue happens while changing a query's label, its URL is being replaced/updated to whatever is currently in the URL bar. PR https://github.com/supercluster-covid-data-portal/ui/pull/41 resolves it.

**Comment by b-f-chan** [comment]
Re-tested on DEV, the above edit issue is fixed.  When renaming and reloading a different query, the proper results are now displayed.  Moving to awaiting release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
