### ISSUE TITLE
Integrate Portal UI with Google Analytics Account

### ISSUE THREAD

**Issue by b-f-chan** [supercluster-covid-data-portal/ui#18]
Placeholder - Integrate portal UI with Google Analytics account for analytics tracking

Access to account to be provided to the team shortly and Property ID

**Comment by justincorrigible** [comment]
See attached PR that adds Tracking Context to the UI. Environment variable set in infra separately from this ticket.

**Comment by b-f-chan** [comment]
Tested on DEV by setting up GA to track traffic against ui.dev.supercluster.cancercollaboratory.org

**Not working:** GA still not detecting traffic, unclear if it is a misconfig in GA, or we have not tagged it properly in the code.

**Comment by b-f-chan** [comment]
Human error - I configured the wrong URL.  Fixed and re-tested on both DEV and Prod sites.  GA traffic now being tracked correctly.  Moving to awaiting release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
