### ISSUE TITLE
Replace `covid cloud` logo

### ISSUE THREAD

**Issue by justincorrigible** [supercluster-covid-data-portal/ui#24]
Using this file, replace the logo displayed on the header of the app.

![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/7d523929-284f-4233-8e19-57e133180b25)

**Comment by b-f-chan** [comment]
Tested successfully on DEV, proper logo appears.  Ready for release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
