### ISSUE TITLE
Add SQON to URLs, and parse queries from a preformated link

### ISSUE THREAD

**Issue by justincorrigible** [supercluster-covid-data-portal/ui#26]
Out-of-the-box, DMS-UI doesn't show the SQON/queries in the URL, which means it is also missing the capacity to parse them from a stored query.
This ticket is meant to track adding that functionality, and the consequent added scope.

**Comment by justincorrigible** [comment]
Finished base implementation reusing and modifying a bit of code from Platform-UI.

Temporary known issue: when scones are cleared, there's a remaining `filter=` in the URL, which is harmless yet not ideal.

**Comment by b-f-chan** [comment]
Tested successfully on DEV.  Blank SQON no longer showing up in URL bar.  Ready for release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
