### ISSUE TITLE
layout displays double scrollbar when base DMS-UI OG theme is modified

### ISSUE THREAD

**Issue by justincorrigible** [supercluster-covid-data-portal/ui#34]
![Screenshot 2021-11-25 at 10.15.38.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/45c4e664-baa7-4b98-b148-c49413af490d)

**Comment by b-f-chan** [comment]
Tested successfully on DEV, double scrollbar issue is gone.  Ready for release.

**Comment by b-f-chan** [comment]
Was released to prod, closing
